---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "scsplit_count"
description: write your description here
keywords:
  - single-cell
  - demultiplex
  - genomics
tools:
  - "scsplit":
      description: "Genotype-free demultiplexing of pooled single-cell RNA-Seq"
      homepage: "https://github.com/jon-xu/scSplit"
      documentation: "https://github.com/jon-xu/scSplit"
      tool_dev_url: "https://github.com/jon-xu/scSplit"
      doi: "https://doi.org/10.1186/s13059-019-1852-7"
      licence: ['MIT']

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', single_end:false ]`
  - bam:
      type: file
      description: BAM index 
      pattern: "*.bam"
  - bai:
      type: file
      description: Sorted BAM file
      pattern: "*.bam"
  - vcf:
      type: file
      description: VCF file
      pattern: "*.vcf"
  - barcodes:
      type: file
      description: Cell barcode list
      pattern: "*.tsv"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', single_end:false ]`
  - ref_filtered: 
      type: file
      description: Reference allele count matrix
  - alt_filtered:
      type: file
      description: Alternative allele count matrix
  - log: 
      type: file 
      description: scSplit log
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@IreneRobles"
maintainers:
  - "@IreneRobles"
